homeYdle:
    pattern:  /
    defaults: { _controller: YdleHubBundle:Home:index }

    
pagesAbout:
    pattern:  /pages/about
    defaults: { _controller: YdleHubBundle:Pages:index }
    
    
configDashboard:
    pattern:  /conf/dashboard
    defaults: { _controller: YdleHubBundle:Config:dashboard }
    

Populate:
    pattern:  /conf/populate
    defaults: { _controller: YdleHubBundle:Config:populate }
    

    
  
  
  
configYdle:
    pattern:  /conf
    defaults: { _controller: YdleHubBundle:Config:index }
configTypeRoom:
  pattern: /conf/typeroom
  defaults: { _controller: YdleHubBundle:Config:typeroom }
configTypeRoomForm:
  pattern: /conf/typeroom/form/{type}
  defaults: { _controller: YdleHubBundle:Config:typeroomForm, type:0 }
configTypeNode:
  pattern: /conf/typenode
  defaults: { _controller: YdleHubBundle:Config:typenode }
configTypeNodeForm:
  pattern: /conf/typenode/form/{type}
  defaults: { _controller: YdleHubBundle:Config:typenodeForm, type:0 }
      
      
#      
#configTypeRoomActivation:
#    pattern:  /conf/typeroom/activation/{type}/{active}
#    defaults: { _controller: YdleHubBundle:Config:typeroomactivation, type:0, active:0 } 
#configTypeRoomDelete:
#    pattern:  /conf/typeroom/delete/{type}
#    defaults: { _controller: YdleHubBundle:Config:typeroomdelete, type:0 } 
